### ISSUE TITLE
back button on ios

### ISSUE THREAD

**Issue by maaikez** [initialxy/cordova-plugin-themeablebrowser#4] opened 2015-03-30 12:25 UTC
First of all, thank you for your plugin. That was just what I needed. Your latest addition (last night?) is also very good.

I installed the plugin on an Android and iOS device. The back button is not working on iOS, on Android it is. 

The back button is showing, but greyed out. After clicking on a link within the webpage, the button will stay greyed out. 

In Android, the button will be white and working on above scenario.

**Comment by initialxy** [comment] 2015-03-30 19:44
Thanks for checking our my plugin and reporting issues back to me. I really appreciate it. I've fixed this issue with the new release, 0.2.1, which is available from Cordova plugin registry. Please take a look.

**Comment by maaikez** [comment] 2015-04-03 13:08
Tested it today, but strangely it's still greyed out. On Android it's working perfectly, but on iOS the back button is never usable (doesn't respond, greyed out). I removed and added the plugin several times and checked if it was really gone, but it really was.

**Comment by initialxy** [comment] 2015-04-03 15:13
Hi @maaikez,
Thanks for retesting this. Could you please check one thing for me? Open

    <cordova_project_root>/plugins/com.initialxy.cordova.themeablebrowser/plugin.xml

What's the version number you see near the top?

Also, I'd like to verify with you the reproduction steps:

1. `backButton` is defined in config and ThemeableBrowser is opened with, let's say Google.
2. Back Button is visible but disabled (alpha 0.5, no response when clicked on it).
3. Navigate to another link, let's say Google Image, wait for page to load.
Observation: back button is still visible but disabled (alpha 0.5, no response when clicked on it).

Is this correct?

Thanks!

**Comment by maaikez** [comment] 2015-04-07 09:55
Yep, version is 0.2.1:
<plugin xmlns="http://apache.org/cordova/ns/plugins/1.0"
           id="com.initialxy.cordova.themeablebrowser"
      version="0.2.1">

About the reproduction steps: 
1. true. Also backButtonCanClose is not defined (so I didn't set it on 'true' or 'false'). 
2. Yep.
3. Indeed. After page load, image is indeed visible but disabled, like you say.

However, when backButtonCanClose is true, there is no problem (so back button is always enabled, alpha 0 and clickable, also when navigating to another link).

**Comment by initialxy** [comment] 2015-04-17 03:11
Thanks for getting back to me. Sorry I was quite occupied for a while. I cannot reproduce this issue on my end. However it has came to my attention that when you update Cordova plugin, Xcode often does not pick up the updates, and builds incrementally without rebuilding the new plugin sources. There was one time I had a syntax error in my code and Xcode built it happily without complain. Please try to clean the project either by running `platforms/ios/cordova/clean` or open your project in Xcode and click on Product -> Clean.

Another theory I have is that perhaps the web site you were using for testing is a single-page-application such that it didn't actually go to a different URL, but simply updated its UI with JavaScript and perhaps AJAX. Try go to Google and click on news or images and see if that helps.

Thanks for your help!

**Comment by maaikez** [comment] 2015-04-17 08:00
The strange thing is that it's working on Android with the same website. So it's not about the website. 
I tried to remove the iOS build, clean it etc. I think I really have the new version installed, but I have no idea how to check that.

Well it's kind of solved with allowing the back button to close the browser. Thx for trying to figure this out.

**Comment by initialxy** [comment] 2015-04-18 03:39
I think I've finally managed to figure out how to reproduce this. My second theory was somewhat closer to the point. It seems like iOS's UIWebView is pretty [terrible with hash change](http://stackoverflow.com/questions/1840355/uiwebview-shouldstartloadwithrequest-only-called-once), which is heavily utilized by modern frameworks like jQuery Mobile, AngularJS, GWT etc. I've managed to make a fix for this issue behaviour. @maaikez, could you please try out my change on develop branch by installing this plugin with command:

    cordova plugin add https://github.com/initialxy/cordova-plugin-themeablebrowser#40f810f885265fe1a7fe1b8eb611fe16579e3e47

If that works, I will make a new release.

Thanks!

**Comment by initialxy** [comment] 2015-04-22 18:36
I've made a new release (0.2.3) that includes fixes for this issue.

**Comment by maaikez** [comment] 2015-04-22 18:57
Thank you! I can not test it yet, but I asked my colleague if he can. I hope I can tell you more later on.

**Closed** 2015-05-06 02:22 UTC
Labels: bug
