### ISSUE TITLE
File upload dialog causes browser window to crash

### ISSUE THREAD

**Issue by aaslun** [initialxy/cordova-plugin-themeablebrowser#53] opened 2015-09-22 11:54 UTC
I am using the themeablebrowser to "wrapp" a website.
On this website there is a form with a file/select input where the user can submit and upload photos from their devices.
When on the iPhone, I click on the file select button the native photo/file dialog pops up. However no matter what i select (take photo, select from camera roll or even cancel) the browser window just collapses (or crashes?). No exit event fires either so I cannot handle this error by launching a new browser window or anything.
Is this a know bug or am I doing something wrong here?
I haven't tried Android yet.

**Comment by aaslun** [comment] 2015-10-05 11:13
Update: I have now tried accessing the native photo/file dialog on an Android device, and the problem is identical: it causes the ThemeableBrowser window to close as well.

**Comment by sencenan** [comment] 2016-03-31 17:52
I could not really help without a website I can test on. Since this bug is report a while back, I am closing it. If you still have the problem, please feel free to resubmit an issue with a website I can reproduce the bug on. Thanks.

**Closed by sencenan** 2016-03-31 17:52 UTC
