### ISSUE TITLE
Please add two error check

### ISSUE THREAD

**Issue by ctl1690** [initialxy/cordova-plugin-themeablebrowser#22] opened 2015-06-01 14:35 UTC
I received memory exception of:
1. NullPointerException (@ThemeableBrowser$ThemeableBrowserClient:onPageStarted:1176) {main}	
2. NullPointerException (@ThemeableBrowser$6$6:onPageFinished:703) {main}

**Comment by initialxy** [comment] 2015-06-08 03:55
Fixed with version 0.2.7.

**Comment by ctl1690** [comment] 2015-06-08 04:25
New NullPointerException:

NullPointerException (@ThemeableBrowser:goForward:476) {main}
NullPointerException (@ThemeableBrowser:goBack:467) {main}	
NullPointerException (@ThemeableBrowser$4:run:307) {main}
NullPointerException (@ThemeableBrowser$6$5:onItemSelected:658) {main}	

ThemeableBrowser version 0.2.6

**Comment by initialxy** [comment] 2015-06-08 04:31
Could you please elaborate on reproduction steps?

**Comment by ctl1690** [comment] 2015-06-08 04:42
Sorry, I can't.  These exceptions received from GA crash report.
And only these information, GA report exception not with callstack....

**Comment by initialxy** [comment] 2015-06-14 08:32
Fixed in version 0.2.9. Please note that due to [Cordova's migration to npm](http://cordova.apache.org/announcements/2015/04/21/plugins-release-and-move-to-npm.html), plugin ID has been updated to `cordova-plugin-themeablebrowser`.

**Closed** 2015-06-14 08:33 UTC
Labels: bug
